apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: {{ include "wordstylecheck.fullname" . }}-db
spec:
  mariaDbRef:
    name: {{ include "wordstylecheck.fullname" . }}-db
  name: wordstylecheck
  characterSet: utf8
  collate: utf8_general_ci